### ISSUE TITLE
Incorrect calculation of StakeAmount when using StakeAppend

### ISSUE THREAD

**Issue by linki** [wanchain/go-wanchain#5]
The calculation for `StakeAmount` ("Power Weight" on https://www.wanscan.org/) of a validator's original creator (the one who called `StakeIn`) is incorrect when `StakeAppend` is used.

##  Example

Given an initial stake of 50,000 WAN and a lock period of 90 days results in a `StakeAmount` of `75,000,000` (the maximum factor 1,500 or [loosely called 1.5x](https://github.com/wanchain/go-wanchain/blob/v2.1.4/core/vm/pos_staking_contracts.go#L1187))

Let's say after 45 days a Partner stakes in, then her weight multiplier is lower because her coins are locked up for only the remaining 45 days. The factor will be around 1,230 (1.23x) according to [CalLocktimeWeight](https://github.com/wanchain/go-wanchain/blob/v2.1.4/core/vm/pos_staking_contracts.go#L1197). So far so good, if the Partner already has some stake then this value is added to the current stake and can only increase the `StakeAmount`. This calculation for PartnerIn is [here](https://github.com/wanchain/go-wanchain/blob/v2.1.4/core/vm/pos_staking_contracts.go#L814). It takes the Partner's current stake weight and adds the transaction's value multiplied by the weight factor to it. The weight factor is based on the remaining lock time.

##  The Problem

However, `StakeAppend` is different: If the original owner uses `StakeAppend` to increase the stake after 45 days then the `StakeAmount ` is re-calculated for the entire stake based on the current weight factor.

Given the example above where 50,000 WAN are locked for 90 days: If the owner `StakeAppend`s 10,000 WAN after 45 days then her `StakeAmount` is re-calculated based on 60,000 WAN staked for the remaining 45 days. This results in a `StakeAmount` of `73,800,000` which is actually lower than the above figure when just 50,000 were staked. Adding more stake worked against the validator in this case. This calculation happens [here](https://github.com/wanchain/go-wanchain/blob/v2.1.4/core/vm/pos_staking_contracts.go#L897) and immediately appears different from the one in `PartnerIn` . To calculate the new `StakeAmount` it takes the entire new stake (`Amount`) and multiplies it by the weight factor for 45 days: 60,000 * 1,230 = `73,800,000`. However, it should rather add the new weighted stake to the current `StakeAmount`: 50,000 * 1,500 + 10,000 * 1,230 = `87,300,000`.

On the blockchain this can be seen for `0x83a1b91ade06bcd2137d953dbdfabe60f78fd157` between blocks 6,374,454 and 6,374,455. Although an additional 11,000 WAN were staked by the validator creator the `StakeAmount` went down from `78,690,000` to `73,440,000`. This can be seen by several other validators that used `StakeAppend` during their lock period.

As far as I can see it all resets correctly when a new stake period is started.

**Comment by zhanglihua-wanglu** [comment]
hi linki
Thanks for the information. we are estimating this issue. thanks again.

**Comment by lolieatcat** [comment]
We have fixed it in testnet gwan-2.1.6-beta.4. And later will release in mainnet.

**Comment by molin0000** [comment]
@linki Thank you very much for your support of the Wanchain project and the team has decided to give you some bonus. Please send your WAN address to techsupport@wanchain.org from your email: Martin.lin****@zalando.de  : )

**Comment by linki** [comment]
@molin0000 Thank you. I'm closing this issue.
